"""
Finaily Research Engine adapter.

This module preserves the original AI stock discovery concept and exposes
structured signals for the Finaily product layer.
"""

from dataclasses import dataclass
from typing import List


@dataclass
class ResearchSignal:
    symbol: str
    theme: str
    score: int
    reason: str


def discover_signals(stocks: List[dict]) -> List[ResearchSignal]:
    signals = []
    for stock in stocks:
        signals.append(
            ResearchSignal(
                symbol=stock.get("symbol", ""),
                theme=stock.get("theme", "AI"),
                score=stock.get("ai_score", 0),
                reason="Generated by Finaily research engine",
            )
        )
    return signals
